# Generated by Django 3.0.1 on 2020-04-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('product_group', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_Image', models.CharField(max_length=50)),
            ],
        ),
    ]
