# Generated by Django 3.0.1 on 2020-04-21 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Product')),
                ('quantity', models.IntegerField(default=0)),
                ('cart_id', models.CharField(max_length=10)),
                ('subtotal_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
