# Generated by Django 3.0.1 on 2020-04-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200421_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10)),
                ('branch_id', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_id',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('cart_state', models.BooleanField()),
                ('cart_created_date', models.DateTimeField()),
                ('cart_expirated_date', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Cart'),
            preserve_default=False,
        ),
    ]
