# Generated by Django 3.0.1 on 2020-04-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200421_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('branch_1', models.CharField(max_length=20)),
                ('branch_2', models.CharField(max_length=20)),
                ('branch_3', models.CharField(max_length=20)),
                ('favorite_drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Product')),
            ],
        ),
    ]
