# Generated by Django 3.0.1 on 2020-04-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200421_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.Branch'),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Product', to_field='product_name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
