# Generated by Django 3.0.1 on 2020-04-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200421_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='order.CartItem'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(db_column='branch_code', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(db_column='branch_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(db_column='branch_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_1',
            field=models.CharField(db_column='FAVORITE_BRANCH_1_C', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_2',
            field=models.CharField(db_column='FAVORITE_BRANCH_2_C', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch_3',
            field=models.CharField(db_column='FAVORITE_BRANCH_3_C', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_drink',
            field=models.ForeignKey(db_column='FAVORITE_DRINK_C', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Product', to_field='product_name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(db_column='MEMBER_ID_C', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(db_column='LASTNAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(db_column='PERSONMOBILEPHONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.CharField(blank=True, db_column='product_image', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(db_column='product_category', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(db_column='product_group', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_column='product_id', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='product_name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(db_column='product_price', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(db_column='product_size', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(db_column='product_type', default='', max_length=50),
        ),
    ]
